name: CI - Python FastAPI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q

      - name: Start FastAPI server (Uvicorn) in background
        run: |
          uvicorn app.main:app --host 127.0.0.1 --port 8000 &
          sleep 5

      - name: Check FastAPI server is running
        run: |
          curl -f http://127.0.0.1:8000/docs || (echo 'Server did not respond' && exit 1)

      - name: Stop Uvicorn server
        run: |
          pkill -f uvicorn || true
